---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - "{{ java_version }}"
      - curl
      - gnupg2
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Rundeck GPG key
  ansible.builtin.get_url:
    url: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
    dest: /etc/apt/keyrings/rundeck.asc
    mode: "0644"

- name: Add Rundeck repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/rundeck.asc] https://packages.rundeck.com/pagerduty/rundeck/any/ any main"
    state: present
    filename: rundeck
    update_cache: true
